# frontend/Dockerfile

FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Serve with a static file server
RUN npm install -g serve

EXPOSE 5173

CMD ["serve", "-s", "dist"]
